import {
    Archive,
    BookOpen,
    BriefcaseBusiness,
    CalendarDays,
    Camera,
    ChartNoAxesCombined,
    Code2,
    Compass,
    Dumbbell,
    Folder,
    GraduationCap,
    Heart,
    Home,
    Lightbulb,
    ListTodo,
    Music,
    Palette,
    Plane,
    Rocket,
    ShoppingCart,
    Star,
    Target,
    Trophy,
    Utensils,
    WalletCards,
    Wrench,
} from '@lucide/vue';

export const boardIconOptions = [
    { value: 'list-todo', component: ListTodo, label: 'Tasks' },
    { value: 'briefcase-business', component: BriefcaseBusiness, label: 'Work' },
    { value: 'calendar-days', component: CalendarDays, label: 'Schedule' },
    { value: 'folder', component: Folder, label: 'Projects' },
    { value: 'heart', component: Heart, label: 'Personal' },
    { value: 'lightbulb', component: Lightbulb, label: 'Ideas' },
    { value: 'plane', component: Plane, label: 'Travel' },
    { value: 'rocket', component: Rocket, label: 'Launch' },
    { value: 'star', component: Star, label: 'Favorites' },
    { value: 'archive', component: Archive, label: 'Archive' },
    { value: 'book-open', component: BookOpen, label: 'Reading' },
    { value: 'camera', component: Camera, label: 'Photos' },
    { value: 'chart-no-axes-combined', component: ChartNoAxesCombined, label: 'Goals' },
    { value: 'code-2', component: Code2, label: 'Development' },
    { value: 'compass', component: Compass, label: 'Explore' },
    { value: 'dumbbell', component: Dumbbell, label: 'Fitness' },
    { value: 'graduation-cap', component: GraduationCap, label: 'Learning' },
    { value: 'home', component: Home, label: 'Home' },
    { value: 'music', component: Music, label: 'Music' },
    { value: 'palette', component: Palette, label: 'Creative' },
    { value: 'shopping-cart', component: ShoppingCart, label: 'Shopping' },
    { value: 'target', component: Target, label: 'Focus' },
    { value: 'trophy', component: Trophy, label: 'Achievements' },
    { value: 'utensils', component: Utensils, label: 'Food' },
    { value: 'wallet-cards', component: WalletCards, label: 'Finance' },
    { value: 'wrench', component: Wrench, label: 'Maintenance' },
] as const;
